title: "ロングモードで遊ぼっ！"
summary: "x86_64のロングモードで遊んだ記録です"
topics: ["amd64", "uefi", "boot"]   # トピック（5つまで）
published: false                    # falseだと下書き
price: 200                          # 有料の場合200〜5000
chapters:
  - 01_uefi_boot-1                  # チャプター1
  - 02_uefi_boot-2                  # チャプター2
  - 03_uefi_boot-3                  # チャプター3
  - 03_uefi_boot-4                  # チャプター4
