title: "ロングモードで遊ぼっ！"
summary: "x86_64のロングモードで遊んだ記録です"
topics: ["amd64", "uefi", "boot"]   # トピック（5つまで）
published: false                    # falseだと下書き
price: 400                          # 有料の場合200〜5000
chapters:
  - 01_uefi_boot-1                  # チャプター1
  - 02_uefi_boot-2                  # チャプター2
  - 03_uefi_boot-3                  # チャプター3
  - 04_uefi_boot-4                  # チャプター4
  - 05_uefi_put_fb-1                # チャプター5
  - 06_uefi_put_fb-2                # チャプター6
  - 07_uefi_keyin-1                 # チャプター7
  - 08_uefi_keyin-2                 # チャプター8
  - 09_uefi_keyin-3                 # チャプター9
  - 10_uefi_mouse                   # チャプター10
  - 11_uefi_timer-1                 # チャプター11
  - 12_uefi_timer-2                 # チャプター12
  - 13_uefi_disk                    # チャプター13
  - 14_uefi_etc_                    # チャプター14
  - 15_uefi_demo                    # チャプター15

