; routine.inc

global disp_str
global disp_nl
global putc
global disp_word_hex
global disp_hex
global disp_byte_hex
global disp_mem
global get_cursor_pos
global set_cursor_pos
global cls
global get_key_b
global power_off
global str_len
global ucase
global lcase
global str_cmp
global line_input
global set_own_seg
global get_tick
global set_tick
global sleep
global _wait
;global decide_next_p_task
global set_own_seg

global tick_ptr
global sleep_sec

global tick_addr
global tick_seg

global ctx_current
global ctx_next
global ctx_temp
